// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6CfNCtHxxL1HmPtsALV_bOq7PpRxVPek',
    appId: '1:9081744655:web:6cf91e71f6ea9056a7a27a',
    messagingSenderId: '9081744655',
    projectId: 'thewall-f0d82',
    authDomain: 'thewall-f0d82.firebaseapp.com',
    storageBucket: 'thewall-f0d82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDCv0ahkglTiBEBQCCS9c63PR2futSpM8',
    appId: '1:9081744655:android:5f454d42dca88aefa7a27a',
    messagingSenderId: '9081744655',
    projectId: 'thewall-f0d82',
    storageBucket: 'thewall-f0d82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALhjxTqPk_M9-ddF1XqcHflyT4j3j0KRw',
    appId: '1:9081744655:ios:25fd0e4a3bba338fa7a27a',
    messagingSenderId: '9081744655',
    projectId: 'thewall-f0d82',
    storageBucket: 'thewall-f0d82.appspot.com',
    iosClientId: '9081744655-7b2a1g07fbunll3ekbuclst9ap4oup89.apps.googleusercontent.com',
    iosBundleId: 'com.example.thewall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALhjxTqPk_M9-ddF1XqcHflyT4j3j0KRw',
    appId: '1:9081744655:ios:81c4fe0cc62d84a4a7a27a',
    messagingSenderId: '9081744655',
    projectId: 'thewall-f0d82',
    storageBucket: 'thewall-f0d82.appspot.com',
    iosClientId: '9081744655-ki4a172k4mhvlicmkq1968kg5dsk5287.apps.googleusercontent.com',
    iosBundleId: 'com.example.thewall.RunnerTests',
  );
}
